// Rich, interconnected default demo dataset for Smart Krishi-Yatra
// Used whenever the database has 0 demo records so all 5 role applications
// (Farmer, Driver, Fleet, Buyer, Admin) are immediately populated with live telemetry.

export const DEFAULT_FARMS = [
  {
    id: "FRM-101",
    name: "Shivneri Organic Farm",
    farmer_name: "Kisan Patil",
    village: "Shirur",
    district: "Pune",
    state: "Maharashtra",
    lat: 18.827,
    lng: 74.373,
    area_acres: 12.5,
    dataset: "demo",
  },
  {
    id: "FRM-102",
    name: "Sahyadri Agro Fields",
    farmer_name: "Ramesh Deshmukh",
    village: "Niphad",
    district: "Nashik",
    state: "Maharashtra",
    lat: 20.078,
    lng: 74.108,
    area_acres: 18.0,
    dataset: "demo",
  },
  {
    id: "FRM-103",
    name: "Godavari Banana Plantation",
    farmer_name: "Suresh Shinde",
    village: "Raver",
    district: "Jalgaon",
    state: "Maharashtra",
    lat: 21.246,
    lng: 75.987,
    area_acres: 25.0,
    dataset: "demo",
  },
];

export const DEFAULT_DRIVERS = [
  {
    id: "DRV-101",
    name: "Santosh Patil",
    phone: "••••9823",
    license_no: "••••4512",
    vehicle_id: "VEH-1",
    status: "on_trip",
    rating: 4.9,
    trips_count: 142,
    dataset: "demo",
  },
  {
    id: "DRV-102",
    name: "Vijay Shinde",
    phone: "••••8841",
    license_no: "••••7890",
    vehicle_id: "VEH-2",
    status: "on_trip",
    rating: 4.8,
    trips_count: 98,
    dataset: "demo",
  },
  {
    id: "DRV-103",
    name: "Ganesh Pawar",
    phone: "••••7712",
    license_no: "••••1123",
    vehicle_id: "VEH-3",
    status: "available",
    rating: 4.9,
    trips_count: 210,
    dataset: "demo",
  },
  {
    id: "DRV-104",
    name: "Rahul Jadhav",
    phone: "••••6634",
    license_no: "••••9944",
    vehicle_id: "VEH-4",
    status: "available",
    rating: 4.7,
    trips_count: 76,
    dataset: "demo",
  },
];

export const DEFAULT_VEHICLES = [
  {
    id: "VEH-1",
    reg_no: "MH13 EF 3302",
    vehicle_type: "12T Multi-Axle",
    capacity_tons: 12,
    refrigerated: false,
    status: "on_trip",
    lat: 18.648,
    lng: 74.015,
    dataset: "demo",
  },
  {
    id: "VEH-2",
    reg_no: "MH15 CD 7702",
    vehicle_type: "8T Medium Truck",
    capacity_tons: 8,
    refrigerated: false,
    status: "on_trip",
    lat: 19.521,
    lng: 73.894,
    dataset: "demo",
  },
  {
    id: "VEH-3",
    reg_no: "MH12 AB 1234",
    vehicle_type: "6T Light Commercial",
    capacity_tons: 6,
    refrigerated: false,
    status: "available",
    lat: 18.52,
    lng: 73.86,
    dataset: "demo",
  },
  {
    id: "VEH-4",
    reg_no: "MH14 XY 5678",
    vehicle_type: "12T Reefer Truck",
    capacity_tons: 12,
    refrigerated: true,
    status: "available",
    lat: 19.997,
    lng: 73.789,
    dataset: "demo",
  },
];

export const DEFAULT_SHIPMENTS = [
  {
    id: "SHP-2026-001",
    farm_id: "FRM-101",
    crop_id: "tomato",
    mandi_id: "apmc-pune",
    quantity_tons: 18,
    harvest_date: new Date().toISOString().slice(0, 10),
    quality_grade: "A",
    priority: "high",
    pooled: true,
    status: "in_transit",
    distance_km: 78,
    eta_minutes: 130,
    transport_cost: 17505,
    pool_savings: 1035,
    expected_amount: 237961,
    payment_status: "held",
    dataset: "demo",
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    crops: { name: "Tomato", emoji: "🍅", perishability: "high", base_price: 1400 },
    mandis: { name: "Pune APMC Market Yard", district: "Pune" },
  },
  {
    id: "SHP-2026-002",
    farm_id: "FRM-102",
    crop_id: "onion",
    mandi_id: "apmc-mumbai",
    quantity_tons: 12,
    harvest_date: new Date().toISOString().slice(0, 10),
    quality_grade: "A",
    priority: "medium",
    pooled: false,
    status: "in_transit",
    distance_km: 165,
    eta_minutes: 240,
    transport_cost: 14200,
    pool_savings: 850,
    expected_amount: 183800,
    payment_status: "held",
    dataset: "demo",
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    crops: { name: "Onion", emoji: "🧅", perishability: "low", base_price: 1650 },
    mandis: { name: "Vashi APMC Mumbai", district: "Thane" },
  },
  {
    id: "SHP-2026-003",
    farm_id: "FRM-103",
    crop_id: "banana",
    mandi_id: "apmc-nagpur",
    quantity_tons: 8,
    harvest_date: new Date().toISOString().slice(0, 10),
    quality_grade: "A",
    priority: "high",
    pooled: true,
    status: "allocated",
    distance_km: 410,
    eta_minutes: 520,
    transport_cost: 21600,
    pool_savings: 1450,
    expected_amount: 126400,
    payment_status: "held",
    dataset: "demo",
    created_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    crops: { name: "Banana", emoji: "🍌", perishability: "high", base_price: 1850 },
    mandis: { name: "Nagpur Kalamna Market", district: "Nagpur" },
  },
];

export const DEFAULT_TRIPS = [
  {
    id: "TRP-101",
    shipment_id: "SHP-2026-001",
    vehicle_id: "VEH-1",
    driver_id: "DRV-101",
    status: "IN_TRANSIT",
    load_tons: 12,
    distance_km: 78,
    eta_minutes: 55,
    payout: 11450,
    progress: 0.65,
    started_at: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    dataset: "demo",
    vehicles: DEFAULT_VEHICLES[0],
    drivers: DEFAULT_DRIVERS[0],
  },
  {
    id: "TRP-102",
    shipment_id: "SHP-2026-001",
    vehicle_id: "VEH-2",
    driver_id: "DRV-102",
    status: "IN_TRANSIT",
    load_tons: 6,
    distance_km: 78,
    eta_minutes: 60,
    payout: 6055,
    progress: 0.58,
    started_at: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    dataset: "demo",
    vehicles: DEFAULT_VEHICLES[1],
    drivers: DEFAULT_DRIVERS[1],
  },
];

export const DEFAULT_GPS_PINGS = [
  {
    id: "GPS-1",
    trip_id: "TRP-101",
    vehicle_id: "VEH-1",
    lat: 18.648,
    lng: 74.015,
    speed_kmph: 48,
    heading_deg: 245,
    recorded_at: new Date(Date.now() - 15 * 1000).toISOString(),
    dataset: "demo",
  },
  {
    id: "GPS-2",
    trip_id: "TRP-102",
    vehicle_id: "VEH-2",
    lat: 18.682,
    lng: 74.089,
    speed_kmph: 52,
    heading_deg: 245,
    recorded_at: new Date(Date.now() - 25 * 1000).toISOString(),
    dataset: "demo",
  },
];

export const DEFAULT_LISTINGS = [
  {
    id: "LST-101",
    shipment_id: "SHP-2026-001",
    crop_id: "tomato",
    farm_id: "FRM-101",
    mandi_id: "apmc-pune",
    quantity_tons: 18,
    price_per_quintal: 1450,
    grade: "A",
    available: true,
    dataset: "demo",
    crops: { name: "Tomato", emoji: "🍅", base_price: 1400 },
    mandis: { name: "Pune APMC Market Yard", district: "Pune" },
    farms: { village: "Shirur", district: "Pune" },
    shipments: { status: "in_transit", quality_grade: "A", harvest_date: "Today" },
  },
  {
    id: "LST-102",
    shipment_id: "SHP-2026-002",
    crop_id: "onion",
    farm_id: "FRM-102",
    mandi_id: "apmc-mumbai",
    quantity_tons: 12,
    price_per_quintal: 1680,
    grade: "A",
    available: true,
    dataset: "demo",
    crops: { name: "Onion", emoji: "🧅", base_price: 1650 },
    mandis: { name: "Vashi APMC Mumbai", district: "Thane" },
    farms: { village: "Niphad", district: "Nashik" },
    shipments: { status: "in_transit", quality_grade: "A", harvest_date: "Today" },
  },
];

export const DEFAULT_ORDERS = [
  {
    id: "ORD-101",
    listing_id: "LST-101",
    crop_id: "tomato",
    quantity_tons: 10,
    total_amount: 145000,
    status: "confirmed",
    created_at: new Date(Date.now() - 3600 * 1000).toISOString(),
    dataset: "demo",
    crops: { name: "Tomato", emoji: "🍅" },
    listings: { grade: "A", price_per_quintal: 1450 },
  },
];

export const DEFAULT_MAINTENANCE = [
  {
    id: "MNT-1",
    vehicle_id: "VEH-3",
    kind: "Periodic Service & Brake Check",
    notes: "10,000 km routine maintenance inspection",
    status: "scheduled",
    cost: 4500,
    dataset: "demo",
  },
];

export const DEFAULT_AUDIT_LOGS = [
  {
    id: "AUD-1",
    actor: "system_orchestrator",
    action: "capacity.allocate",
    entity: "SHP-2026-001",
    detail: "18t Tomato load split into 12t (MH13 EF 3302) + 6t (MH15 CD 7702). Saved ₹1,035 pooling discount.",
    dataset: "demo",
    created_at: new Date(Date.now() - 60 * 1000).toISOString(),
  },
  {
    id: "AUD-2",
    actor: "Santosh Patil",
    action: "trip.accepted",
    entity: "TRP-101",
    detail: "Driver accepted trip for Shirur to Pune APMC",
    dataset: "demo",
    created_at: new Date(Date.now() - 120 * 1000).toISOString(),
  },
];
