/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDemoRouteImport } from './routes/admin.demo'
import { Route as AdminNetworkRouteImport } from './routes/admin.network'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as BuyerIndexRouteImport } from './routes/buyer.index'
import { Route as BuyerOrdersRouteImport } from './routes/buyer.orders'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'
import { Route as DriverTripsRouteImport } from './routes/driver.trips'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as FarmerMarketRouteImport } from './routes/farmer.market'
import { Route as FarmerNewRouteImport } from './routes/farmer.new'
import { Route as FarmerShipmentsRouteImport } from './routes/farmer.shipments'
import { Route as FarmerWalletRouteImport } from './routes/farmer.wallet'
import { Route as FleetIndexRouteImport } from './routes/fleet.index'
import { Route as FleetDriversRouteImport } from './routes/fleet.drivers'
import { Route as FleetMaintenanceRouteImport } from './routes/fleet.maintenance'
import { Route as FleetVehiclesRouteImport } from './routes/fleet.vehicles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemoRoute = AdminDemoRouteImport.update({
  id: '/admin/demo',
  path: '/admin/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNetworkRoute = AdminNetworkRouteImport.update({
  id: '/admin/network',
  path: '/admin/network',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/admin/operations',
  path: '/admin/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/buyer/',
  path: '/buyer/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerOrdersRoute = BuyerOrdersRouteImport.update({
  id: '/buyer/orders',
  path: '/buyer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/driver/earnings',
  path: '/driver/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripsRoute = DriverTripsRouteImport.update({
  id: '/driver/trips',
  path: '/driver/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/farmer/',
  path: '/farmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerMarketRoute = FarmerMarketRouteImport.update({
  id: '/farmer/market',
  path: '/farmer/market',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerNewRoute = FarmerNewRouteImport.update({
  id: '/farmer/new',
  path: '/farmer/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerShipmentsRoute = FarmerShipmentsRouteImport.update({
  id: '/farmer/shipments',
  path: '/farmer/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerWalletRoute = FarmerWalletRouteImport.update({
  id: '/farmer/wallet',
  path: '/farmer/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIndexRoute = FleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetDriversRoute = FleetDriversRouteImport.update({
  id: '/fleet/drivers',
  path: '/fleet/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetMaintenanceRoute = FleetMaintenanceRouteImport.update({
  id: '/fleet/maintenance',
  path: '/fleet/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetVehiclesRoute = FleetVehiclesRouteImport.update({
  id: '/fleet/vehicles',
  path: '/fleet/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/demo': typeof AdminDemoRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/trips': typeof DriverTripsRoute
  '/farmer/market': typeof FarmerMarketRoute
  '/farmer/new': typeof FarmerNewRoute
  '/farmer/shipments': typeof FarmerShipmentsRoute
  '/farmer/wallet': typeof FarmerWalletRoute
  '/fleet/drivers': typeof FleetDriversRoute
  '/fleet/maintenance': typeof FleetMaintenanceRoute
  '/fleet/vehicles': typeof FleetVehiclesRoute
  '/admin/': typeof AdminIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/fleet/': typeof FleetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/demo': typeof AdminDemoRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/trips': typeof DriverTripsRoute
  '/farmer/market': typeof FarmerMarketRoute
  '/farmer/new': typeof FarmerNewRoute
  '/farmer/shipments': typeof FarmerShipmentsRoute
  '/farmer/wallet': typeof FarmerWalletRoute
  '/fleet/drivers': typeof FleetDriversRoute
  '/fleet/maintenance': typeof FleetMaintenanceRoute
  '/fleet/vehicles': typeof FleetVehiclesRoute
  '/admin': typeof AdminIndexRoute
  '/buyer': typeof BuyerIndexRoute
  '/driver': typeof DriverIndexRoute
  '/farmer': typeof FarmerIndexRoute
  '/fleet': typeof FleetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/demo': typeof AdminDemoRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/buyer/orders': typeof BuyerOrdersRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/trips': typeof DriverTripsRoute
  '/farmer/market': typeof FarmerMarketRoute
  '/farmer/new': typeof FarmerNewRoute
  '/farmer/shipments': typeof FarmerShipmentsRoute
  '/farmer/wallet': typeof FarmerWalletRoute
  '/fleet/drivers': typeof FleetDriversRoute
  '/fleet/maintenance': typeof FleetMaintenanceRoute
  '/fleet/vehicles': typeof FleetVehiclesRoute
  '/admin/': typeof AdminIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/fleet/': typeof FleetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/demo'
    | '/admin/network'
    | '/admin/operations'
    | '/buyer/orders'
    | '/driver/earnings'
    | '/driver/trips'
    | '/farmer/market'
    | '/farmer/new'
    | '/farmer/shipments'
    | '/farmer/wallet'
    | '/fleet/drivers'
    | '/fleet/maintenance'
    | '/fleet/vehicles'
    | '/admin/'
    | '/buyer/'
    | '/driver/'
    | '/farmer/'
    | '/fleet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/demo'
    | '/admin/network'
    | '/admin/operations'
    | '/buyer/orders'
    | '/driver/earnings'
    | '/driver/trips'
    | '/farmer/market'
    | '/farmer/new'
    | '/farmer/shipments'
    | '/farmer/wallet'
    | '/fleet/drivers'
    | '/fleet/maintenance'
    | '/fleet/vehicles'
    | '/admin'
    | '/buyer'
    | '/driver'
    | '/farmer'
    | '/fleet'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/demo'
    | '/admin/network'
    | '/admin/operations'
    | '/buyer/orders'
    | '/driver/earnings'
    | '/driver/trips'
    | '/farmer/market'
    | '/farmer/new'
    | '/farmer/shipments'
    | '/farmer/wallet'
    | '/fleet/drivers'
    | '/fleet/maintenance'
    | '/fleet/vehicles'
    | '/admin/'
    | '/buyer/'
    | '/driver/'
    | '/farmer/'
    | '/fleet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminDemoRoute: typeof AdminDemoRoute
  AdminNetworkRoute: typeof AdminNetworkRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  BuyerOrdersRoute: typeof BuyerOrdersRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverTripsRoute: typeof DriverTripsRoute
  FarmerMarketRoute: typeof FarmerMarketRoute
  FarmerNewRoute: typeof FarmerNewRoute
  FarmerShipmentsRoute: typeof FarmerShipmentsRoute
  FarmerWalletRoute: typeof FarmerWalletRoute
  FleetDriversRoute: typeof FleetDriversRoute
  FleetMaintenanceRoute: typeof FleetMaintenanceRoute
  FleetVehiclesRoute: typeof FleetVehiclesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
  FleetIndexRoute: typeof FleetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demo': {
      id: '/admin/demo'
      path: '/admin/demo'
      fullPath: '/admin/demo'
      preLoaderRoute: typeof AdminDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/network': {
      id: '/admin/network'
      path: '/admin/network'
      fullPath: '/admin/network'
      preLoaderRoute: typeof AdminNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/buyer'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/orders': {
      id: '/buyer/orders'
      path: '/buyer/orders'
      fullPath: '/buyer/orders'
      preLoaderRoute: typeof BuyerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/driver/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/trips': {
      id: '/driver/trips'
      path: '/driver/trips'
      fullPath: '/driver/trips'
      preLoaderRoute: typeof DriverTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/farmer'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/market': {
      id: '/farmer/market'
      path: '/farmer/market'
      fullPath: '/farmer/market'
      preLoaderRoute: typeof FarmerMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/new': {
      id: '/farmer/new'
      path: '/farmer/new'
      fullPath: '/farmer/new'
      preLoaderRoute: typeof FarmerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/shipments': {
      id: '/farmer/shipments'
      path: '/farmer/shipments'
      fullPath: '/farmer/shipments'
      preLoaderRoute: typeof FarmerShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/wallet': {
      id: '/farmer/wallet'
      path: '/farmer/wallet'
      fullPath: '/farmer/wallet'
      preLoaderRoute: typeof FarmerWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/': {
      id: '/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof FleetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/drivers': {
      id: '/fleet/drivers'
      path: '/fleet/drivers'
      fullPath: '/fleet/drivers'
      preLoaderRoute: typeof FleetDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/maintenance': {
      id: '/fleet/maintenance'
      path: '/fleet/maintenance'
      fullPath: '/fleet/maintenance'
      preLoaderRoute: typeof FleetMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/vehicles': {
      id: '/fleet/vehicles'
      path: '/fleet/vehicles'
      fullPath: '/fleet/vehicles'
      preLoaderRoute: typeof FleetVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminDemoRoute: AdminDemoRoute,
  AdminNetworkRoute: AdminNetworkRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  BuyerOrdersRoute: BuyerOrdersRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverTripsRoute: DriverTripsRoute,
  FarmerMarketRoute: FarmerMarketRoute,
  FarmerNewRoute: FarmerNewRoute,
  FarmerShipmentsRoute: FarmerShipmentsRoute,
  FarmerWalletRoute: FarmerWalletRoute,
  FleetDriversRoute: FleetDriversRoute,
  FleetMaintenanceRoute: FleetMaintenanceRoute,
  FleetVehiclesRoute: FleetVehiclesRoute,
  AdminIndexRoute: AdminIndexRoute,
  BuyerIndexRoute: BuyerIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
  FarmerIndexRoute: FarmerIndexRoute,
  FleetIndexRoute: FleetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
